#!/bin/bash
if test -f ./remote.conf; then
    source ./remote.conf
fi 
if test -f ./local.conf; then
    source ./local.conf
fi 

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

while :
do
    goversion=$(go version)
    if [ 0 -ne $? ]
    then
        echo -e "\033[1mgo developer tools need to be installed\033[0m (https://go.dev/doc/install)"
        echo -e "Press enter once go is installed"
        read -r goversion
    else
        break
    fi
done

while :
do
    gccommit=$(git-conventional-commits --version)
    if [ 0 -ne $? ]
    then
        echo -e "\033[1mgit-conventional-commits needs to be install\033[0m (https://github.com/qoomon/git-conventional-commits)"
        echo -e "Press enter once it is installed"
        read -r goversion
    else
        break
    fi
done

# get bot token
if [ -z $DEVELOPMENT_BOT_TOKEN ]
then
    echo -e "\033[1mdiscord bot token to use locally\033[0m (https://discord.com/developers/applications/)"
    read -r DEVELOPMENT_BOT_TOKEN
    echo "DEVELOPMENT_BOT_TOKEN=$DEVELOPMENT_BOT_TOKEN" >> ./local.conf
fi

# get bot token
if [ -z $DEVELOPMENT_GUILD_ID ]
then
    echo -e "\033[1mdiscord guild id to use for commands\033[0m"
    read -r DEVELOPMENT_GUILD_ID
    echo "DEVELOPMENT_GUILD_ID=$DEVELOPMENT_GUILD_ID" >> ./local.conf
fi