#!/bin/bash

if test -f ./remote.env; then
    source ./remote.env
fi 
if test -f ./local.env; then
    source ./local.env
fi 

export DEVELOPMENT_BOT_TOKEN=$DEVELOPMENT_BOT_TOKEN
export DEVELOPMENT_GUILD_ID=$DEVELOPMENT_GUILD_ID
go run ./examples/bot